CrateConfig_Sections:
- MOTR_CONFIG
- WORKLOAD_SPEC
MOTR_CONFIG:
  MOTR_LOCAL_ADDR: 192.168.91.119@tcp:12345:4:1
  MOTR_HA_ADDR: 192.168.91.119@tcp:12345:1:1
  PROF: 0x7000000000000001:0x37
  PROCESS_FID: 0x7200000000000001:0x1a
  LAYOUT_ID: 4
  IS_OOSTORE: 1
  IS_READ_VERIFY: 0
  TM_RECV_QUEUE_MIN_LEN: 16
  MAX_RPC_MSG_SIZE: 262144
  IDX_SERVICE_ID: 1
  ADDB_INIT: 1
WORKLOAD_SPEC:
- WORKLOAD:
    WORKLOAD_TYPE: 0
    WORKLOAD_SEED: tstamp
    LOG_LEVEL: 2
    NUM_KVP: 128
    NXRECORDS: default
    RECORD_SIZE: 32
    MAX_RSIZE: 1M
    OP_COUNT: 32
    WARMUP_PUT_CNT: 0
    WARMUP_DEL_RATIO: 0
    KEY_PREFIX: random
    KEY_ORDER: ordered
    INDEX_FID: <7800000000000001:0>
    PUT: 0
    DEL: 0
    GET: 100
    NEXT: 0
