delete_account_temp_cred:
  account_name: "delacctempcred_acc"
  email_id: "{}@seagate.com"
  password: "oOPdW3a5sMcVfchrdiJGDSIrIu49ByTsprb/jIQbowU="
  password_reset: False
  bucket_name_prefix: "delacctempcred-bkt-"
  acc_create_failed_msg: "Failed to create an account"

test_4519:
  temp_access_key: "aljalkjfoiwej12324c"
  temp_secret_key: "akjhfkjahfq972rudajdakjda"
  temp_session_token: "tGM7DSpjJVGHhRc7pflI2grRf4jkINRaCvME+sDW"

test_4520:
  account_name: "delacctempcred_acc_1"
  temp_access_key: "lakjdlkajfq9872dhsakj"
  temp_secret_key: "KalkjfkafIUYDuiqy2894"
  temp_session_token: "tGM7DSpjJVGHhRc7pflI2grRf4jkINRaCvME+sDW"

test_4521:
  time_duration: 1200

test_4522:
  bucket_name: "delacctempcred-bkt-4522"

test_4525:
  bucket_name: "delacctempcred-bkt-4525"
  time_duration: 1200

test_4526:
  time_duration: 5000

test_4692:
  bucket_name: "delacctempcred-bkt-4692"

