test_8660_8664_8665_8668:
    file_size: 100
    total_parts: 10

test_8669:
    file_size: 100
    total_parts: 10

test_8661:
    file_size: 3000
    total_parts: 3

test_8663:
    file_size: 50
    total_parts: 5

test_8666:
    file_size: 5005
    total_parts: 1001
    max_parts: 1000

test_8670:
    file_size: 500
    s3_configs:
        - "default.s3.max_concurrent_requests"
        - "default.s3.max_queue_size"
        - "default.s3.multipart_threshold"
        - "default.s3.multipart_chunksize"
        - "default.s3.max_bandwidth"
        - "default.s3.addressing_style"
    multipart_s3_config_values:
        - "20"
        - "10000"
        - "64MB"
        - "16MB"
        - "50MB/s"
        - "path"
    default_s3_config_values:
        - "10"
        - "1000"
        - "8MB"
        - "5MB"
        - "None"
        - "auto"

test_8672:
    file_size: 180
    total_parts: 30

test_8673:
    file_size: 5000000
    total_parts: 10000

test_8674:
    file_size: 180
    total_parts: 30

test_8922:
    file_size: 50005
    total_parts: 10001
    err_msg: "InvalidPart"

test_8923:
    file_size: 50000
    total_parts: 10000
    max_list_parts: 1000 # Limit for maximum number of parts returned for a list parts request

test_8924:
    file_size: 20
    total_parts: 5
    err_msg: "EntityTooSmall"

test_8925:
    file_size: 11000
    total_parts: 2
    err_msg: "EntityTooLarge"

test_8926:
    file_size: 10
    total_parts: 2
    total_mp_uploads: 1000

test_8927:
    file_size: 10
    total_parts: 2
    total_mp_uploads: 1001
    max_uploads: 1000

test_8928:
    file_size: 500
    s3_configs: "default.s3.max_concurrent_requests"
    max_concurrent_requests: "40"
    default_max_concurrent_requests: "10"

test_8929:
    file_size: 500
    s3_configs: "default.s3.multipart_threshold"
    multipart_threshold: "64MB"
    default_multipart_threshold: "8MB"

test_631:
    error_msg: "An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation:
    One or more of the specified parts could not be found. The part might not have been uploaded,
    or the specified entity tag might not have matched the part's entity tag."
    wrong_json:
        -   ETag: d41d8cd98f00b204e9800998ecf8427e
            PartNumber: 1
        -   ETag: d41d8cd98876362482364f00b204e980
            PartNumber: 2
