PerfDB:
  hostname: cftic1.pun.seagate.com:27017,cftic2.pun.seagate.com:27017,apollojenkins.pun.seagate.com:27017/?authSource=performance_db&replicaSet=rs0
  # hostname: ssc-vm-3541.colo.seagate.com:27017/?authSource=performance_db
  database: performance_db
  collection:
    R1: results_1
    R2: results_2
  auth:
    full_access_user: <db_username>
    full_access_password: <db_password>
