test_4920:
  duration: 86400

test_4922:
  user_list:
    - "csm_admin_user"
    - "csm_user_manage"
    - "csm_user_monitor"
  record_count: 10000
  end_date: 10
  max_record_count: 10010
  hrs: 24
  min: 60
  sec: 60

test_4915:
  epoc_time_diff: 86400
