common:
  num_users: 10
  iterations: 5
test_1133:
  status_code: 401

test_36448:
  invalid_key: "!@#$%^&*!@#$%^&*"
  valid_key: "0555b35654ad16*"

test_38088:
  error_code: 12288
  message_id: "NoSuchUser"  
  message_index: 0
test_38914:
  payloads:
    - {"system":null}
    - {"caps":[]}
    - {"type":"rgw"}
    - {"tenant":""}
    - {"system":"false"}
    - {"admin":"false"}
    - {"random":"acbv"}
  error_code: 4099
  message_id: "MalformedRequest"
  message_index: 6
test_38092:
  error_code: 4099
  message_id: "MalformedRequest"
  message_index: 4
test_38969:
  error_code: 12288
  message_id: "KeyExists"
  message_index: 0
test_39028:
  error_code: 12288
  message_id: "InvalidCapability"
  message_index: 0
test_37778:
  error_code: 4099
  message_id: "empty key"
  message_index_1: 0
  message_index_2: 1
test_37777:
  error_code: 12288
  message_id: "KeyExists"
  message_index: 0
test_37782:
  error_code: 4104
  message_id: "PermissionDenied"
  message_index: 0
test_37783:
  error_code: 4104
  message_id: "PermissionDenied"
  message_index: 0
test_37779:
  error_code: 4099
  message_id: "empty key"
  message_index: 2
test_38093:
  error_code: 4099
  message_id: "empty key"
  message_index_1: 1
  message_index_2: 0
test_38095:
  error_code: 4099
  message_id: "MalformedRequest"
  message_index_1: 1
  message_index_2: 2
test_38097:
  error_code: 4099
  message_id: "MalformedRequest"
  message_index_1: 1
  message_index_2: 3
test_38103:
  error_code: 4099
  message_id: "MalformedRequest"
  message_index_1: 4
  message_index_2: 5
test_38107:
  error_code: 12288
  message_id: "EmailExists"
  message_index: 0
test_38091:
  error_code: 4099
  message_id: "empty key"
  message_index: 1
test_38094:
  error_code: 4099
  message_id: "empty key"
  message_index: 1
test_39401:
  error_code: 12288
  message_id: "UserAlreadyExists"
  message_index: 0
test_42273:
  error_code: 4099
  message_id: "MalformedRequest"
  message_index_1: 14
  message_index_2: 2
test_42284:
  max_entries: 5
  max_entries_2: 15
test_42274:
  ran_int: 10
test_42287:
  error_code: 4104
  message_id: "PermissionDenied"
  message_index: 0
test_42288:
  error_code: 4104
  message_id: "PermissionDenied"
  message_index: 0
test_42289:
  error_code: 12288
  message_id: "UserAlreadyExists"
  message_index: 0
test_42290:
  error_code: 4111
  message_id: "UnauthorizedError"
  message_index: 0 
