test_1914:
  payload:
    password: 'QiX19+/DsLfV9kXp2ORsP0eTU5Ky9QBWhKg6EkfrupQ='
    reset_access_key: "false" 
test_1915:
  response_msg:
    error_code: 4101
    message_id: "Access denied for account"
    message_index: 0
test_28924:
  response_msg:
    error_code: 4099
    message_id: "Invalid request body"
    message: "Invalid request body: {'secret_key': ['Length must be between 8 and 40.']}"
test_28773:
  response_msg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 4
test_28925:
  response_msg:
    error_code: 4099
    message_id: "NA"
    message: 'Only access_key or secret_key is provided.'
test_28926:
  response_msg:
    error_code: 4099
    message_id: "NA"
    message: 'Only access_key or secret_key is provided.'
test_28927:
  response_msg:
    error_code: 12288
    message_id: "UserAlreadyExists"
    message_index: 0
test_28928:
  response_msg:
    error_code: 12288
    message_id: "EmailExists"
    message_index: 0
test_28929:
  response_msg:
    error_code: 12288
    message_id: "KeyExists"
    message_index: 0
test_28931:
  response_msg:
    error_code: 12288
    message_id: "MaxAccountLimitExceeded"
    message: 'The request was rejected because maximum limit(i.e 1000) of account creation has exceeded.'
