test_5001:
  invalid_sortby: "roles"
  response_msg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index : 20 
test_5004:
  invalid_sortdir: "abc"
  error_code: 4099
  message_id: "MalformedRequest"
  message_index: 21
test_5000:
  valid_sortby: 
    - "username"
    - "created_time"
    - "updated_time"
test_5003:
  valid_sortdir: 
    - "asc"
    - "desc"
test_5016:
  user:
    - "valid"
    - "manage"
    - "monitor"
  payload_manage:
    role: "manage"
    password: 'qiLA1WIqNyX0Uy4gz1RuqEiM2ZCVHAok0Ht6y0HS04E='  
  payload_monitor:
    role: "monitor"
    password: 'qiLA1WIqNyX0Uy4gz1RuqEiM2ZCVHAok0Ht6y0HS04E='
test_7421:
  data:
    - "Testuser@12345" 
    - "monitor"
test_7420:
  data:
    - "valid"
    - "manage"
    - "monitor"
    - "Testuser@12345"
test_7411:
  data:
    - "Testuser@12345" 
    - "root"
test_1229:
  data:
    - "valid"
    - "manage"
    - "monitor"
    - "Testuser@12345"
test_5019:
  user:
    - "valid"
    - "manage"
    - "monitor"
    - "Testuser@12345"
  payload_login: 
    username: ""
    password: 'RyG8qZZccLkU7VQHimSNGBWm5kur98DznEn/y62J1j0='
test_7422:
  payload_manage:
    role: "monitor"
    old_password: ""
  payload_monitor:
    role: "manage"
    old_password: ""
  response_manage:
    error_code: 4101
    message_id: "user_permission_denied"
    message_index: 1
    error_format_args: ""
test_7412:
  payload:
    role: "monitor"
  payload_admin:
    role: "monitor"
    old_password: ""
  response_admin:
    error_code: 4101
    message_id: "user_permission_denied"
    message_index: 0
    error_format_args: ""
test_7408:
  payload:
    username: "newuser"
    old_password: ""
  response_mesg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 22
test_6220:
  response_duplicate_csm_manage_user:
    error_code: 4103
    message_id: "users_already_exists"
    message_index: 0
  response_duplicate_csm_monitor_user:
    error_code: 4103
    message_id: "users_already_exists"
    message_index: 0
  response_duplicate_s3_account:
    error_code: 12288
    message_id: "EntityAlreadyExists"
    message_index: 0
    error_format_args: 
      account_name: ""
test_5021:
  response_message: 
    message: "User Deleted Successfully."
test_5005:
  response_msg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 21
test_5002:
  response_msg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 20
test_5020:
  response_msg:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 23
test_5017:
  invalid_user_id: "invaliduser123"
  payload:
    role: "manage"
    password: '6CJC8Fy705Jm/KgS7XWgTdGOmn6GtAkAwGoPRS4bLVM='
  response_msg:
    error_code: 4101
    message_id: "users_not_found"
    message_index: 0
test_5010:
  invalid_user_id: "invaliduser123"
  response_msg:
    error_code: 4101
    message_id: "users_not_found"
    message_index: 0
test_5018:
  range:
    - 4
  payload_invalid_password_1:
    password: 'RyG8qZZccLkU7VQHimSNGBWm5kur98DznEn/y62J1j0='
  payload_invalid_password_2:
    password: 'UJC4S6AjJFIr4RkqLuER6O+cK4fxLny8WyTUcxaVrtQ='
  payload_invalid_password_3:
    password: 'YSkJh8yANAnRF4vOgeFODMx6CmVTuuLLMu1kdL2uONA='
  payload_invalid_role:
    role: "abc"
  payload_invalid_password_role:
    role: "abc"
    password: 'UJC4S6AjJFIr4RkqLuER6O+cK4fxLny8WyTUcxaVrtQ='
  invalid_password_resp_1:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 8
  invalid_password_resp_2:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 9
  invalid_password_resp_3:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 10
  invalid_role_resp:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 11
  invalid_password_role_resp_1:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 12
  invalid_password_role_resp_2:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 13
test_1173:
  data: 
    - "Testuser@12345"
  status_code: 401
test_1172:
  username: "incorrectuser123"
  password: '1oa2EwRk/urr4oKeEiO6jCg8e74EVStVfw8WVZyw0An1fW0ingjZANtJ51xljjY4'
  status_code: 401
test_7362:
  password: 'qiLA1WIqNyX0Uy4gz1RuqEiM2ZCVHAok0Ht6y0HS04E='
test_25278:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 4
test_25280:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 1
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
test_25282:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 4
    email_id: "testuser@seagate.com"
test_25275:
    error_code: 4104
    message_id: "PermissionDenied"
    message_index: 1
test_25279:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 1
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
test_25281:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 4
    email_id: "testuser@seagate.com"
test_25277:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index: 3
test_25276:
    error_code: 4104
    message_id: "PermissionDenied"
    message_index: 0
test_25286:
    error_code: 4104
    message_id: "user_permission_denied"
    message_index: 2
test_25283:
    error_code: 4104
    message_id: "user_permission_denied"
    message_index_1: 2
    message_index_2: 3
test_25285:
    error_code: 4104
    message_id: "user_permission_denied"
    message_index_1: 2
    message_index_2: 3
test_28501:
    new_password: "+ZfWaNAnxT4p39QOZ1A2QG+OWYJmgI4dEk9WcG6wS04="
    reset_password: True
test_28502:
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 8
test_28505:
    new_password: "D1wkl0ge5mqvq+6Ioah57QHUCdjbn2CarpIqocu2PkQ="
    reset_password: True
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 19
test_28517:
    new_password: "+ZfWaNAnxT4p39QOZ1A2QG+OWYJmgI4dEk9WcG6wS04="
    reset_password: True
    token_expire_timeout: 3600
test_28513:
    password: "1oa2EwRk/urr4oKeEiO6jCg8e74EVStVfw8WVZyw0An1fW0ingjZANtJ51xljjY4"
    status_code: 401
    error_code: 4111
    message_id : "UnauthorizedError"
    message_index: 1
test_28512:
    username: "incorrectuser123ABC"
    status_code: 401
    error_code: 4111
    message_id: "UnauthorizedError"
    message_index: 1
test_28515:
    password: "7uY5HlnrQgqcNMg1dG2AdUcU/344qPhx70zTTytHqPc="
    status_code: 401
    error_code: 4111
    message_id: "UnauthorizedError"
    message_index: 1
test_28514:
    username: "123"
    status_code: 401
    error_code: 4111
    message_id: "UnauthorizedError"
    message_index: 1
test_28511:
    status_code: 400
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 4
test_28510:
    status_code: 400
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 4
test_28509:
    status_code: 400
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 25
test_28508:
    status_code: 400
    error_code: 4099
    message_id: "MalformedRequest"
    message_index: 25
test_32171:
    error_code: 4104
    message_id: "update_not_allowed"
    message_index_1: 0
    message_index_2: 5
test_32174:
    new_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
test_32178:
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
    email_id: "test@seagate.com"
test_32180:
    error_code: 4104
    message_id: "user_permission_denied"
    message_index: 2
test_32181:
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
test_44802:
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
    new_password: "+ZfWaNAnxT4p39QOZ1A2QG+OWYJmgI4dEk9WcG6wS04="
test_44803:
    current_password: "puUqs4Ns/l/fh6teILWN1FPFu3RZogVZ0SbtsMpbkOA="
