test_4920:
  duration: 86400

test_4922:
  user_list:
    - "csm_admin_user"
    - "csm_user_manage"
    - "csm_user_monitor"
  record_count: 10000
  end_date: 10
  max_record_count: 10010
  hrs: 24
  min: 60
  sec: 60

test_4915:
  epoc_time_diff: 86400

epoc_time_diff: 6400

test_22332:
  duration: 86400

test_22334:
  duration: 86400

test_22335:
  duration: 86400
  username: "incorrectuser1234"
  password: '1oa2EwRk/urr4oKeEiO6jCg8e74EVStVfw8WVZyw0An1fW0ingjZANtJ51xljjY4'
  status_code: 401

test_22336:
  duration: 86400

test_22337:
  duration: 86400
  delay: 20

