vm_params:
  uname: "Wy3kDTDH70ZfSqD0S7EinXiUNzdqtUcsoGmduDd3Ofo="
  passwd: "ItoPnYPoGVTg+IzlbzMr9wCO/aRjevBu55jkx+13WUI="

common_params:
  loop_count: 11
  power_on_time: 900
  power_off_time: 900
  pod_eviction_time: 360
  pod_joinback_time: 180
  1sec_delay: 1
  5sec_delay: 5
  10sec_delay: 10
  20sec_delay: 20
  30sec_delay: 30
  60sec_delay: 60
  90sec_delay: 90
  degraded_wait_delay: 200
  thread_join_delay: 120.0

s3_operation_data:
  no_csm_users: 10
  no_buckets_per_users: 50
  obj_per_bucket: 200

5gb_mpu_data:
  file_size: 4800
  total_parts: 100

copy_obj_data:
  bkt_cnt: 5
  bkt_multi: 10

s3_bucket_data:
  no_buckets_for_deg_deletes: 150
  workload_sizes_mbs: [1, 2, 4, 8, 16, 32, 64, 128]
  no_bck_background_deletes: 300

s3_bench_workloads: ["0b", "1Kb", "16Kb", "32Kb", "64Kb", "128Kb", "256Kb", "512Kb",
                     "1Mb", "4Mb", "8Mb", "16Mb", "32Mb", "64Mb", "128Mb", "256Mb", "512Mb"]

s3_bench_large_workloads: ["1Gb", "2Gb", "3Gb", "4Gb", "5Gb"]

bg_bucket_ops:
  no_del_buckets: 100

near_full_system_percent: 60
