clients: 1
samples: 500
size: '128Mb'
loop_count: 10
#sizes in size_list are in Mb
size_list: [1, 2, 3, 4, 5, 6, 7]
rgw_restart_cnt: 5

test_41234:
  nclients: 10
  nsamples: 30

test_41235:
  nclients: 10
  nsamples: 10

#overwrite object test
test_41230:
  max_object_size: 512 #Mb
  overwrite_cnt: 200

test_42246:
  num_loop: 300
