password: "NxcdYlhvOOic8ahZt9JHNoP0JVNOq2/J3B2RinQd0jY="
new_password: "htj410PciGqrH099Ew4b7lmLUc/DnJJZhmzBEey8ON4="
user_name_prefix: "iamuser"
jcloud_cfg:
    jcloud_tool: "jcloud"
    jclient_tool: "jclient"
    jclient_properties_path: "scripts/jcloud/jclient.properties"
    jcloud_properties_path: "scripts/jcloud/jcloud.properties"
    jcloud_path: "scripts/jcloud/jcloudclient.jar"
    jclient_path: "scripts/jcloud/jclient.jar"
    jcloud_cmd: "java -jar scripts/jcloud/jcloudclient.jar"
    jclient_cmd: "java -jar scripts/jcloud/jclient.jar"
minio_cfg:
    create_bkt_cmd: "./mc mb s3/{0}"
    upload_obj_cmd: "./mc cp {0} s3/{1}"
    download_obj_cmd: "./mc cp s3/{0}/{1} {2}"
    list_obj_cmd: "./mc ls s3/{0}"
    cr_two_bkt_cmd: "./mc mb s3/{0} s3/{1}"
    lst_bkt_cmd: "./mc ls s3"
    no_of_buckets: 1000
    dlt_bkt_cmd: "./mc rb s3/{0}"
    dlt_obj: "./mc rm s3/{0}/{1}"
    display_cont: "./mc cat s3/{0}/{1}"
    head_obj_n_lines: "./mc head -n {0} s3/{1}/{2}"
    head_obj: "./mc head s3/{0}/{1}"
    upload_data: "Blaclbox minio client Testsuite\nMinio client operations\nPerforming head operation on object"
s3cmd_cfg:
    s3cmd_tool: "s3cmd"
    success_msg_del: "Bucket '{}/' remove"
    success_msg_crt: "Bucket '{}/' create"
    bucket_name: "s3cmdbucket-nm{}"
    bucket_name_prefix: "s3cmdbucket-nm"
    delete_msg: "delete: '{}'"
    file_creation: "echo 'Hello World...' > {}"
    count_bkt: 100
    make_bucket: "mb"
    put_bucket: "put"
    remove_bucket: "rb"
    del_obj: "del"
    rm_bkt: "rm"
    bkt_path_format: "s3://{}"
    list_bucket: "ls"
    list_all_buckets: "la"
    get: "get"
    force: "--force"
    recursive: "--recursive"
    upload_msg: "done"
    success_msgs:
        - "Location:"
        - "Payer:"
        - "Expiration Rule:"
        - "Policy:"
        - "CORS:"
        - "ACL:"
s3fs_cfg:
  s3fs_tool: "s3fs"
  success_msg: "Bucket '{}/' create"
  bucket_name: "s3fsbucket-{}"
  bkt_name_prefix: "s3fsbucket-"
  passwd_file: "-o passwd_file=/etc/passwd-s3fs"
  url: "-o url={}"
  path_style: "-o use_path_request_style"
  dbglevel: "-o dbglevel=info"
  make_dir_cmd: "mkdir"
  dir_name: "/mnt/s3fstest{}"
  new_dir_name: "s3fstest1{}"
  dir_to_rm: "/mnt/s3fstest"
  cmd_check_mount: "mount | grep {}"
  rm_file_cmd: "rm -rf"
  unmount_cmd: "umount"
  dd_cmd: "dd"
  input_file: "if=/dev/zero of={}"
  count: "count={}"
  block_size: "bs={}"
  create_file_cmd: "touch"
  file_name: "file1{}"
  ls_mnt_dir_cmd: "ls"
  #server certificate won't be checked against the available certificate authorities.
  no_check_certificate: False
  #When ssl_verify_hostname 0, do not verify the SSL certificate against the hostname,default="2".
  ssl_verify_hostname: True
  #s3fs is always using SSL session cache, this option make SSL session cache disable.
  nosscache: False
