PerfDB:
    hostname : cftic1.pun.seagate.com:27017,cftic2.pun.seagate.com:27017,apollojenkins.pun.seagate.com:27017/?authSource=performance_db&replicaSet=rs0
    database: performance_db
    collection: 
        R1: results_1
        R2: results_2
    auth:
        full_access_user: perfpro
        full_access_password: PerfPro
